# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Email Report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily Report
          body: Report attached.
          to: